### ISSUE TITLE
Problems with token authentication

### ISSUE THREAD

**Issue by frankenstein91** [opentelekomcloud/docs#1]
I try to get this working https://docs.otc.t-systems.com/en-us/api/apiug/apig-en-api-180328003.html

but I get a error 401. Could you please tell me where I get the information. 

Thank you

**Comment by Nils-Magnus** [comment]
Is this still an issue? If so, please explain, what you did, what you expected, and what you experienced.

It might be that you are mixing up "token" with your API key, AK/SK, or your credentials. You receive a valid token from the Open Telekom Cloud when you access the IAM service and authenticate with your credentials.

**Comment by Nils-Magnus** [comment]
For general questions see also https://community.open-telekom-cloud.com/ .

**Comment by frankenstein91** [comment]
the problem is over a year old. I can't remember.

**Comment by Nils-Magnus** [comment]
Ok, fair enough. Sorry for the delay, we reorganized recently our teams to address those questions in a more timely manner in the future. So, if you can't remember, I shall close the issue then if I don't read from you within a few days. Please re-open if you have any future questions.
